//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoNature.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeafPlant_PropertiesToTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeafPlant_PropertiesToTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoNature.Components.LeafPlant.PropertiesToTranslate", typeof(LeafPlant_PropertiesToTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CenterPoint=&quot;Středový bod&quot;
        ///OneLengthPixels=&quot;Jednotková délka v pixelech&quot;
        ///FylotaxisAngle=&quot;Fylotaktický úhel&quot;
        ///LeafTemplate=&quot;Vzor listu&quot;
        ///AlreadyGrownState=&quot;Fáze růstu&quot;
        ///CenterPointParentAbsoluteLocation=&quot;Absolutní umístění středového bodu v rodiči&quot;
        ///CurrentTimeAfterLastGrowth=&quot;Čas od posledního přírůstku&quot;
        ///DeathTimeSpanFromAveragePart=&quot;&quot;
        ///IsDead=&quot;Mrtev&quot;
        ///LifeTimer=&quot;Časovač života&quot;
        ///TimeToAverageDieAfter=&quot;&quot;
        ///TimeToGrowOneStepAfter=&quot;&quot;
        ///ZeroStateOneLengthPixels=&quot;&quot;
        ///OnePartGrowOneLengthPixels=&quot;&quot;
        ///.
        /// </summary>
        internal static string LeafPlant_PropertiesToTranslate_cs_CZ {
            get {
                return ResourceManager.GetString("LeafPlant_PropertiesToTranslate_cs_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CenterPoint=&quot;&quot;
        ///OneLengthPixels=&quot;&quot;
        ///FylotaxisAngle=&quot;&quot;
        ///LeafTemplate=&quot;&quot;
        ///AlreadyGrownState=&quot;&quot;
        ///CenterPointParentAbsoluteLocation=&quot;&quot;
        ///CurrentTimeAfterLastGrowth=&quot;&quot;
        ///DeathTimeSpanFromAveragePart=&quot;&quot;
        ///IsDead=&quot;&quot;
        ///LifeTimer=&quot;&quot;
        ///TimeToAverageDieAfter=&quot;&quot;
        ///TimeToGrowOneStepAfter=&quot;&quot;
        ///ZeroStateOneLengthPixels=&quot;&quot;
        ///OnePartGrowOneLengthPixels=&quot;&quot;
        ///.
        /// </summary>
        internal static string LeafPlant_PropertiesToTranslate_en_GB {
            get {
                return ResourceManager.GetString("LeafPlant_PropertiesToTranslate_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CenterPoint=&quot;&quot;
        ///OneLengthPixels=&quot;&quot;
        ///FylotaxisAngle=&quot;&quot;
        ///LeafTemplate=&quot;&quot;
        ///AlreadyGrownState=&quot;&quot;
        ///CenterPointParentAbsoluteLocation=&quot;&quot;
        ///CurrentTimeAfterLastGrowth=&quot;&quot;
        ///DeathTimeSpanFromAveragePart=&quot;&quot;
        ///IsDead=&quot;&quot;
        ///LifeTimer=&quot;&quot;
        ///TimeToAverageDieAfter=&quot;&quot;
        ///TimeToGrowOneStepAfter=&quot;&quot;
        ///ZeroStateOneLengthPixels=&quot;&quot;
        ///OnePartGrowOneLengthPixels=&quot;&quot;.
        /// </summary>
        internal static string LeafPlant_PropertiesToTranslate_en_US {
            get {
                return ResourceManager.GetString("LeafPlant_PropertiesToTranslate_en_US", resourceCulture);
            }
        }
    }
}
