//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoNature.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Leaf_PropertiesToTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Leaf_PropertiesToTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoNature.Components.Leaf.PropertiesToTranslate", typeof(Leaf_PropertiesToTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsoluteCenterPointLocation=&quot;&quot;
        ///CenterPoint=&quot;&quot;
        ///GrowFrom_CenterPoint=&quot;&quot;
        ///AccurateLogarithmicSpiral=&quot;&quot;
        ///OneLengthPixels=&quot;&quot;
        ///OnePartPossitinon=&quot;&quot;
        ///BeginingAnglePhase=&quot;&quot;
        ///Veins=&quot;&quot;
        ///VeinsFractalisation=&quot;&quot;
        ///VeinsBorderReachPart=&quot;&quot;
        ///CentralVeinPixelThickness=&quot;&quot;
        ///Fill=&quot;&quot;
        ///BorderColor=&quot;&quot;
        ///BorderPen=&quot;&quot;
        ///VitalFillColor=&quot;&quot;
        ///CurrentFillColor=&quot;&quot;
        ///CurrentFillBrush=&quot;&quot;
        ///VitalFillBrush=&quot;&quot;
        ///VeinsColor=&quot;&quot;
        ///LeftCurveTension=&quot;&quot;
        ///RightCurveTension=&quot;&quot;
        ///CurveBehindCenterPoint=&quot;&quot;
        ///SmoothTop=&quot;&quot;
        ///InvertedCurving=&quot;&quot;
        ///ContinueAfterInve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaf_PropertiesToTranslate_cs_CZ {
            get {
                return ResourceManager.GetString("Leaf_PropertiesToTranslate_cs_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsoluteCenterPointLocation=&quot;&quot;
        ///CenterPoint=&quot;&quot;
        ///GrowFrom_CenterPoint=&quot;&quot;
        ///AccurateLogarithmicSpiral=&quot;&quot;
        ///OneLengthPixels=&quot;&quot;
        ///OnePartPossitinon=&quot;&quot;
        ///BeginingAnglePhase=&quot;&quot;
        ///Veins=&quot;&quot;
        ///VeinsFractalisation=&quot;&quot;
        ///VeinsBorderReachPart=&quot;&quot;
        ///CentralVeinPixelThickness=&quot;&quot;
        ///Fill=&quot;&quot;
        ///BorderColor=&quot;&quot;
        ///BorderPen=&quot;&quot;
        ///VitalFillColor=&quot;&quot;
        ///CurrentFillColor=&quot;&quot;
        ///CurrentFillBrush=&quot;&quot;
        ///VitalFillBrush=&quot;&quot;
        ///VeinsColor=&quot;&quot;
        ///LeftCurveTension=&quot;&quot;
        ///RightCurveTension=&quot;&quot;
        ///CurveBehindCenterPoint=&quot;&quot;
        ///SmoothTop=&quot;&quot;
        ///InvertedCurving=&quot;&quot;
        ///ContinueAfterInve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaf_PropertiesToTranslate_en_GB {
            get {
                return ResourceManager.GetString("Leaf_PropertiesToTranslate_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsoluteCenterPointLocation=&quot;&quot;
        ///CenterPoint=&quot;&quot;
        ///GrowFrom_CenterPoint=&quot;&quot;
        ///AccurateLogarithmicSpiral=&quot;&quot;
        ///OneLengthPixels=&quot;&quot;
        ///OnePartPossitinon=&quot;&quot;
        ///BeginingAnglePhase=&quot;&quot;
        ///Veins=&quot;&quot;
        ///VeinsFractalisation=&quot;&quot;
        ///VeinsBorderReachPart=&quot;&quot;
        ///CentralVeinPixelThickness=&quot;&quot;
        ///Fill=&quot;&quot;
        ///BorderColor=&quot;&quot;
        ///BorderPen=&quot;&quot;
        ///VitalFillColor=&quot;&quot;
        ///CurrentFillColor=&quot;&quot;
        ///CurrentFillBrush=&quot;&quot;
        ///VitalFillBrush=&quot;&quot;
        ///VeinsColor=&quot;&quot;
        ///LeftCurveTension=&quot;&quot;
        ///RightCurveTension=&quot;&quot;
        ///CurveBehindCenterPoint=&quot;&quot;
        ///SmoothTop=&quot;&quot;
        ///InvertedCurving=&quot;&quot;
        ///ContinueAfterInve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaf_PropertiesToTranslate_en_US {
            get {
                return ResourceManager.GetString("Leaf_PropertiesToTranslate_en_US", resourceCulture);
            }
        }
    }
}
