//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoNature.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeafPlant_PropertiesToTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeafPlant_PropertiesToTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoNature.Components.LeafPlant.PropertiesToTranslate", typeof(LeafPlant_PropertiesToTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase of growth.
        /// </summary>
        internal static string AlreadyGrownState {
            get {
                return ResourceManager.GetString("AlreadyGrownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central point.
        /// </summary>
        internal static string CenterPoint {
            get {
                return ResourceManager.GetString("CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute placement of central point in parent.
        /// </summary>
        internal static string CenterPointParentAbsoluteLocation {
            get {
                return ResourceManager.GetString("CenterPointParentAbsoluteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from last growth.
        /// </summary>
        internal static string CurrentTimeAfterLastGrowth {
            get {
                return ResourceManager.GetString("CurrentTimeAfterLastGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial average deviation from the length of life.
        /// </summary>
        internal static string DeathTimeSpanFromAveragePart {
            get {
                return ResourceManager.GetString("DeathTimeSpanFromAveragePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fylotaxis angle.
        /// </summary>
        internal static string FylotaxisAngle {
            get {
                return ResourceManager.GetString("FylotaxisAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string IsDead {
            get {
                return ResourceManager.GetString("IsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf template.
        /// </summary>
        internal static string LeafTemplate {
            get {
                return ResourceManager.GetString("LeafTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life timer.
        /// </summary>
        internal static string LifeTimer {
            get {
                return ResourceManager.GetString("LifeTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leafy plant seen from above.
        /// </summary>
        internal static string NameTranslated {
            get {
                return ResourceManager.GetString("NameTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit length in pixels.
        /// </summary>
        internal static string OneLengthPixels {
            get {
                return ResourceManager.GetString("OneLengthPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit length increment after one step growth in pixels.
        /// </summary>
        internal static string OnePartGrowOneLengthPixels {
            get {
                return ResourceManager.GetString("OnePartGrowOneLengthPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average length of life.
        /// </summary>
        internal static string TimeToAverageDieAfter {
            get {
                return ResourceManager.GetString("TimeToAverageDieAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One step growth time.
        /// </summary>
        internal static string TimeToGrowOneStepAfter {
            get {
                return ResourceManager.GetString("TimeToGrowOneStepAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit length of zero phase of the growth in pixels.
        /// </summary>
        internal static string ZeroStateOneLengthPixels {
            get {
                return ResourceManager.GetString("ZeroStateOneLengthPixels", resourceCulture);
            }
        }
    }
}
